PROJBASE=$(CURDIR)/..

#########################################
#                Target                 #
#########################################
SUBDIR= .\

#########################################
#      header and lib dependancy        #
#########################################
INC_DIR= -I. -I.. \

STATIC_LIB= \

SHARED_LIB_DIR=
SHARED_LIB=

#########################################
#              compiler                 #
#########################################
include $(PROJBASE)/build/makefile.compiler

#########################################
#              rules                    #
#########################################
include $(PROJBASE)/build/makefile.compile.rules

